ebook_metadata:
  title: དཀོན་ཅོག་འགྲེལ། །
  authors:
  - མཛད་པ་པོ། རོང་ཟོམ་ཆོས་བཟང།
  sku: SHE-010-1
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
web_metadata:
  title:
    en: The Precious Jewel:A Commentary on the Secret Essence of Tantra
    bo: དཀོན་ཅོག་འགྲེལ།
  collection:
    en: Shechen Tantra Series–  Book 10
    bo: ''
  author:
    en: Rong Shom Chosang
    bo: རོང་ཟོམ་ཆོས་བཟང།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-010-1
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-010-1.epub
  description:
    en: ''
    bo: ''
